# ============================================================================
# Generate include/font_cn.h: 12x12 bitmap glyphs for the Chinese UI strings.
#
# Rasterizes a fixed whitelist of characters from the Fusion Pixel 12px
# monospaced font (same TTF as the ESPHome config's font_cn, OFL licensed;
# pixel style matches the Press Start 2P aesthetic), thresholds to 1-bit,
# optically centers each glyph in the 12x12 cell, and emits a C++ table.
# At the native 12px size the pixel font rasterizes with zero anti-aliasing,
# so every glyph lands 1:1 on the grid (11x11 ink box for all CJK glyphs).
# Bitmap layout matches Canvas::draw_bitmap(): row-major, 2 bytes per row
# (12px), MSB = leftmost.
#
# Usage:  python tools/gen_cn_font.py
# Run from the repo root (paths are resolved relative to this script).
# ============================================================================

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ---- Configuration ---------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
FONT_PATH = REPO_ROOT / "esphome" / "fonts" / "fusion-pixel-12px-monospaced-zh_hans.ttf"
FONT_SIZE = 12  # native design size of the pixel font -> crisp 1:1 grid
CELL = 12  # glyph cell in pixels
THRESHOLD = 128  # alpha >= THRESHOLD -> lit pixel

# Whitelist: every Chinese character rendered by ui_pages.cpp.
# 温湿度 空气质量 表情 | 偏冷 偏热 干燥 潮湿 舒适 正常 | 优 良 中 差 很差 未知
CHARS = "温湿度空气质量表情优良中差很未知偏冷热干燥潮舒适正常"


def render_char(font: ImageFont.FreeTypeFont, ch: str) -> list[int] | None:
    """Rasterize one char into a 12x12 1-bit bitmap. None if blank."""
    # Oversized canvas so nothing clips before optical centering.
    pad = 6
    canvas = Image.new("L", (CELL + 2 * pad, CELL + 2 * pad), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((pad, pad), ch, fill=255, font=font)

    bbox = canvas.getbbox()  # (l, t, r, b) of ink
    if bbox is None:
        return None

    # Optical centering: shift ink so the glyph sits mid-cell (clip at edges).
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    off_x = (pad + (CELL - w) // 2) - bbox[0]
    off_y = (pad + (CELL - h) // 2) - bbox[1]

    canvas = canvas.transform(
        canvas.size,
        Image.AFFINE,
        (1, 0, -off_x, 0, 1, -off_y),
        resample=Image.NEAREST,
    )
    canvas = canvas.crop((pad, pad, pad + CELL, pad + CELL))

    bits = []
    for row in range(CELL):
        b0 = b1 = 0
        for col in range(CELL):
            if canvas.getpixel((col, row)) >= THRESHOLD:
                if col < 8:
                    b0 |= 0x80 >> col
                else:
                    b1 |= 0x80 >> (col - 8)
        bits += [b0, b1]
    return bits


def ascii_preview(bits: list[int]) -> str:
    lines = []
    for row in range(CELL):
        line = ""
        for col in range(CELL):
            byte = bits[row * 2 + (col // 8)]
            line += "#" if byte & (0x80 >> (col % 8)) else "."
        lines.append(line)
    return "\n".join(lines)


def main() -> None:
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    glyphs: dict[str, list[int]] = {}
    for ch in CHARS:
        bits = render_char(font, ch)
        if bits is None:
            raise SystemExit(f"ERROR: '{ch}' rendered blank")
        if any(bits[i * 2] & 0x0F or bits[i * 2 + 1] & 0xF0 for i in range(CELL)):
            print(f"WARNING: '{ch}' ink touches cell edge (may be clipped)")
        glyphs[ch] = bits

    lines = [
        "#pragma once",
        "// ============================================================================",
        "// font_cn.h -- GENERATED by tools/gen_cn_font.py, do not edit by hand.",
        "//",
        "// 12x12 1-bit glyphs (Fusion Pixel 12px, same TTF as the ESPHome",
        "// config's font_cn) for the Chinese UI whitelist: " + CHARS,
        "//",
        "// Bitmap layout = Canvas::draw_bitmap() format: row-major,",
        "// 2 bytes per row (12px wide), MSB = leftmost pixel.",
        "// Cell advance is 13px (12px glyph + 1px spacing); see Canvas::text_width().",
        "// ============================================================================",
        "",
        "#include <cstdint>",
        "",
        "namespace FontCN",
        "{",
        f"    constexpr int W = {CELL};",
        f"    constexpr int H = {CELL};",
        "    constexpr int ADVANCE = 13; // glyph width + 1px spacing",
        "",
        "    struct Glyph",
        "    {",
        "        uint16_t cp;      // Unicode code point",
        "        uint8_t bits[24]; // 12 rows x 2 bytes, MSB = leftmost",
        "    };",
        "",
        "    inline const Glyph GLYPHS[] = {",
    ]
    for ch, bits in glyphs.items():
        cp = ord(ch)
        data = ", ".join(f"0x{b:02X}" for b in bits)
        lines.append(f"        {{0x{cp:04X}, {{{data}}}}}, // U+{cp:04X} '{ch}'")
    lines += [
        "    };",
        "",
        "    // Linear scan over the small whitelist; returns nullptr if missing.",
        "    inline const Glyph *find(uint32_t cp)",
        "    {",
        "        for (const Glyph &g : GLYPHS)",
        "            if (g.cp == cp)",
        "                return &g;",
        "        return nullptr;",
        "    }",
        "",
        "} // namespace FontCN",
    ]

    out = Path(__file__).resolve().parent.parent / "include" / "font_cn.h"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(glyphs)} glyphs, {out.stat().st_size} bytes)")

    # Preview all glyphs side by side for quick visual inspection.
    for start in range(0, len(glyphs), 8):
        group = list(glyphs.items())[start : start + 8]
        rows = [""] * CELL
        header = ""
        for ch, bits in group:
            header += f"{'[' + ch + ']':<12}"
            art = ascii_preview(bits).split("\n")
            for r in range(CELL):
                rows[r] += art[r] + " "
        print("\n" + header)
        print("\n".join(rows))


if __name__ == "__main__":
    main()
